ProblemPage shows problem.message
enspyrco/crowdleague pull request #317
Opened 2020-12-23 05:18 UTC by T-Davis

Part of [Error Handling UC 1 ](https://github.com/enspyrco/crowdleague/issues/274)

2020-12-23 05:39 UTC, nickmeinhold requested changes
Beautiful mate!  Happy to add a class description comment (per my review comment)?

2020-12-23 05:39 UTC, nickmeinhold commented on lib/widgets/shared/problem_page.dart
> +class ProblemPage extends StatelessWidget {
Any interest in dropping a really brief class description comment at the top?  Class just seems kinda naked without one :-)  I am aware of the hypocrisy but I look forward to being asked to put some clothes on my classes!

2020-12-24 04:18 UTC, tamari-gray approved these changes
lgtm! so good to see some problem pr's!

2020-12-24 05:32 UTC, nickmeinhold approved these changes
Brilliant!  Thanks mate!

2020-12-24 05:44 UTC, merged